### ISSUE TITLE
Team interest in user post history, in addition to comments?

### ISSUE THREAD

**Issue by Nathansbud** [Dear-Blueno/dearblueno#49]
### Summary

Obviously the platform is intended to be largely anonymous, but I think that it might be useful to add post history to a user profile (in addition to comment history). Feature request motivated by my accidental reposts, [#5705](https://www.dearblueno.net/post/5705) & [#5826](https://www.dearblueno.net/post/5826), because I hadn't realized I already posted.

I do suspect this is probably infeasible if the submission form is a fancy wrapper around a Google form, and the moderators handle the approval process of posts. Maybe include user IDs with submissions into the approval queue (in a way that the moderators can't see)? I didn't dig too much into the codebase to check.

### Basic Example

User goes to their profile; right now, a comment feed with context is provided. Proposed change is to either: integrate top-level posts into this feed (a la Reddit user summary), or have a separate tab for posts/comments (a la Sidechat).

### Drawbacks

The ability to see user posts on their profile somewhat goes against the anonymous aims of the platform. Hence, maybe have it so a logged in user can only see their own posts? You can already see comments on user profiles, though, so maybe that's a non-issue?

**Comment by j-f1** [comment]
Please don’t add this, the whole point is that the posts are truly anonymous and nobody can use them to take action against their authors. If you want unaccountable people to know all the stuff you post go on Sidechat :)

**Comment by nicholasvadasz** [comment]
As you mentioned, the main issue with this feature is the attaching of identifying user information to posts (i.e. the "author"-ifying of posts), which is something we don't do. Since Dear Blueno is student-built and student-ran, this true anonymity makes it so that users can rest assured that members of their community won't be able to track their posts back to them, and moderators/developers carry less liability since there is truly no avenue to de-anonymize posts.

It's feasible to imagine that we could built out some way for logged in users to "opt in" to de-anonymizing their posts, likely via some toggle on the settings page. Still, it's not clear if this feature is entirely worth the tradeoffs it would entail. We are hoping that our bookmarking feature, as well perhaps improving our current searching system, might help alleviate this "accidental repost" problem you mentioned. Regardless, enabling users to more easily follow the posts they're interested in is something we are always thinking about, so we will make sure to keep this suggestion in mind when considering new ways to improve our site's existing content system. Thanks for the feedback!

**Comment by Nathansbud** [comment]
Makes sense—assumed there was some existing association with users and posts since comments can be de-anonymized!

**Comment by NicholasBottone** [comment]
I have considered potentially adding some sort of cryptographic keys to posts, with the goal of allowing comments to be shown as "OP" without needing to associate posts with the user that submitted them, or allowing users to earn/"redeem" XP for posts they created. (For example, after submitting a post, the poster is given a private key that could verify they submitted a post when it matches with the post's public key.) However, this would not allow for the automatic association with a post in a profile's post history as you described. Additionally, the key system is complicated enough that it is unclear if anyone would ever take advantage of it, plus it adds a vector of identifying the original poster, when it is unclear if that is desired on the platform. An alternative system of identifying the original poster like this cryptographic system is still much more likely for us to implement than complete post history association.
